# 프로그래머스 코딩테스트 연습 SQL 문제
# cte 활용

# 재귀식을 활용하여 0 ~ 23 TABLE 생성
WITH RECURSIVE CTE AS (
    SELECT 0 AS N 
    UNION ALL 
    SELECT N + 1 FROM CTE
    WHERE N < 23)
    
SELECT A.N AS HOUR, IFNULL(B.COUNT,0) 
FROM CTE AS A
LEFT JOIN ( # LEFT JOIN을 통해 ANIMAL_OUTS TABLE에 없는 시각의 ROW 생성
    SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
    ) AS B
ON A.N = B.HOUR;
